### ISSUE TITLE
Log in BUG

### ISSUE THREAD

**Issue by Rogzy-DB** [DecouvreBitcoin/sovereign-university#100]
2 bug i see.

If you start the process ot create an account. set up a usename ( or not even) and then tab out to another windows ( to get a password) and come back it has exited the log in pop up. 

Second bug is this message: ( Also it should be 5 caracter so i can have Rogzy)

![Image](https://github.com/DecouvreBitcoin/sovereign-university/assets/131364678/2646defc-d470-4624-890f-85402da05246)

**Comment by trigger67** [comment]
I fixed the 2nd bug.
1st is still there.
