### ISSUE TITLE
Change name of CUBO + course

### ISSUE THREAD

**Issue by Rogzy-DB** [DecouvreBitcoin/sovereign-university#109]
CUbo + est un cours de develoopment. 

Debutant 
intermedaire
advanced  ( crypto)

DEV  (cubo+ )

![Image](https://github.com/DecouvreBitcoin/sovereign-university/assets/131364678/e7f36f9b-6298-4649-8886-8db4b853bcf6)

Donc le mettre en 4eme posistion ou dans advances pour simplifier. 

Sur le graph des cours le mettre tous en bas apres les cours LN

**Comment by trigger67** [comment]
Fait
