### ISSUE TITLE
fix footer link

### ISSUE THREAD

**Issue by Rogzy-DB** [DecouvreBitcoin/sovereign-university#157]
Fix les liens du footer: 

À propos de

    [Notre histoire](https://sovereignuniversity.org/resources/books/1/en)
-> https://sovereignuniversity.org/manifesto

    [Sponsoring & contributeurs](https://sovereignuniversity.org/resources/books/1/en)
-> Page About

    [Professeurs](https://sovereignuniversity.org/resources/books/1/en)
-> ????

[Aidez-nous](https://sovereignuniversity.org/resources/books/1/en)
-> ???

    [Dons](https://sovereignuniversity.org/resources/books/1/en)
-> ???

    [Marchandising](https://sovereignuniversity.org/resources/books/1/en)
-> SHOP

Termes et conditions
-> ????

**Comment by trigger67** [comment]
Je ne comprends pas le contenu de l'issue.
Faut-il ajouter des liens ? Les modifier ? Lesquels ? Vers ou ?
