### ISSUE TITLE
UI optimization suggestions for .md files

### ISSUE THREAD

**Issue by LoicPandul** [DecouvreBitcoin/sovereign-university#198]
Quelques suggestions d'amélioration de l'UI pour l'interprétation des fichiers .md, afin de mieux mettre en valeur les tuto : 
- Rendre les liens hypertextes plus visibles en les mettant en gras, de couleur orange et soulignés, afin qu'ils ressortent clairement du texte et collent avec la charte graphique ;
- Pour le code inline (et éventuellement pour les blocs de code, je n'ai pas encore testé), adopter une présentation `similaire à celle de GitHub`, où le code inline est surligné en gris avec une police typique.

Merci par avance les gars :)

@trigger67  @Asi0Flammeus

**Comment by LoicPandul** [comment]
Pour les blocs de code, c'est ok. Ça ressort en fond noir donc c'est parfais. Je vais utiliser cette mise en forme plutôt que le code inline en attendant 👍

**Comment by LoicPandul** [comment]
En fait, ça met directement du bloc de code même lorsque c'est mis en forme en inline sur le .md ^^
![md](https://github.com/DecouvreBitcoin/sovereign-university/assets/137194052/275f402f-ff6d-4918-820e-dfc7a38b6994)
![planb site](https://github.com/DecouvreBitcoin/sovereign-university/assets/137194052/58564cf9-205f-4ece-8c9f-78b3543bae18)

**Comment by LoicPandul** [comment]
Autre souci que je viens de voir, mais pour celui-là c'est peut-être ma faute : la première ligne dans les blocs de code est dans une police d’écriture différente des autres lignes du même bloc de code, ce qui n'est pas très joli. 
![Capture d'écran 2024-03-13 163724](https://github.com/DecouvreBitcoin/sovereign-university/assets/137194052/be22950b-94e5-4210-a4ab-7af14a1d67cb)

**Comment by trigger67** [comment]
@kevinmulier is this 100% fixed?

**Comment by kevinmulier** [comment]
@trigger67 yes, this is fixed, now following #282
