### ISSUE TITLE
fix image on web page tab url in browser

### ISSUE THREAD

**Issue by Rogzy-DB** [DecouvreBitcoin/sovereign-university#230]
we are still with the previous logo when putting planB as a tab on the browser

![Image](https://github.com/DecouvreBitcoin/sovereign-university/assets/131364678/e3ae7706-ba2d-4f8a-a8c8-750f99bc14ce)

**Comment by trigger67** [comment]
devs: it's been a very long time we changed it, it's probably in the browsers cache
