### ISSUE TITLE
refine Builder page

### ISSUE THREAD

**Issue by louneskmt** [DecouvreBitcoin/sovereign-university#24]
https://www.figma.com/file/foyvlfIOyL88zXCZXSQbzK/DecouvreBitcoin?type=design&node-id=1140-71909&t=Zde1vNb4lEooz2kN-4

**Comment by louneskmt** [comment]
Assigned to @guillaumehussong. Can you please comment so I can assign this the proper way? 😁

**Comment by guillaumehussong** [comment]
👋

**Comment by louneskmt** [comment]
Done, thanks!
