### ISSUE TITLE
cards for links of tutorials and resources inside courses text

### ISSUE THREAD

**Issue by mumacadam** [DecouvreBitcoin/sovereign-university#242]
today, links are just shown, and don't promote the resources and tutorials they are linked to. the idea is to introduce cards to visualise better these links.
the card for tutorial exists (quick redesign to make)
but the resources also should be carded the same way (books, podcasts, anything else? > to brainstorm and delimit)

![Image](https://github.com/DecouvreBitcoin/sovereign-university/assets/144212410/17e0bd73-b26c-411f-9900-bd1d45713c81)

![Image](https://github.com/DecouvreBitcoin/sovereign-university/assets/144212410/fee44770-5cf3-4d10-bbc4-d894ca242267)

**Comment by kevinmulier** [comment]
In PR #404
