### ISSUE TITLE
Small bug in code blocks in the tutorials

### ISSUE THREAD

**Issue by LoicPandul** [DecouvreBitcoin/sovereign-university#282]
I just discovered a small bug in the English translation tutorials: when they are accessed for the first time, the code blocks appear with `[object Object]` instead of the actual content:
![bug](https://github.com/DecouvreBitcoin/sovereign-university/assets/137194052/99fc760d-69e8-498a-b945-74c7a87469f1)

Once the webpage is refreshed, the code block returns to normal:
![sans bug](https://github.com/DecouvreBitcoin/sovereign-university/assets/137194052/d44e01bb-7683-408b-b61e-56dbb3b489a3)

**Comment by trigger67** [comment]
@kevinmulier can you have a look ?

**Comment by kevinmulier** [comment]
Cannot reproduce
