### ISSUE TITLE
redesign of course page & info banner for bizschool

### ISSUE THREAD

**Issue by mumacadam** [DecouvreBitcoin/sovereign-university#289]
redesign of course page, including a dynamic banner - only for the biz school, and other ux improvements, to be implemented on all courses.

dev link : 

https://www.figma.com/file/1fto3tLdJH7hOcbQ7vT9dg/PlanB-Network---Work-in-progress?type=design&node-id=3087-36477&mode=dev

![Image](https://github.com/DecouvreBitcoin/sovereign-university/assets/144212410/1efde5ff-5d38-4ca9-934b-348864ad820f)

**Comment by trigger67** [comment]
@mumacadam will be live on testnet in 5min
