### ISSUE TITLE
Rendering issue with the inline LaTeX.

### ISSUE THREAD

**Issue by LoicPandul** [DecouvreBitcoin/sovereign-university#435]
We have an issue we can't resolve regarding the data: the inline LaTeX doesn't display on the site, while the LaTeX blocks do display correctly. For example, there is quite a bit of LaTeX on this page: https://testnet.planb.network/fr/courses/btc204/2871d594-414e-4598-a830-91c9eb84dfb8

We tried adding a space between the "$" symbols, but it still doesn't work.

Thank you in advance for your help!

**Comment by trigger-xyz** [comment]
@kevinmulier what should we do of this issue ?

**Comment by kevinmulier** [comment]
We can close it, it's solved @trigger67
