### ISSUE TITLE
Rendering issue with the citations

### ISSUE THREAD

**Issue by LoicPandul** [DecouvreBitcoin/sovereign-university#442]
The new citation formatting makes them appear as _[object Object]_ instead of the citation in the markdown. This issue is present only on the mainnet.
For example: https://planb.network/fr/tutorials/privacy/stonewall
![Capture d'écran 2024-08-01 144628](https://github.com/user-attachments/assets/5111f48b-9ad8-4b87-83b9-c71f7d0d0782)

**Comment by trigger-xyz** [comment]
Issue is fixed on dev.
It will be deployed soon.

**Comment by LoicPandul** [comment]
Okay, thank you. I should have guessed ^^, sorry. I'm closing the issue.
