### ISSUE TITLE
Teacher dashboard - Course detail

### ISSUE THREAD

**Issue by trigger-xyz** [DecouvreBitcoin/sovereign-university#493]

**Comment by kevinmulier** [comment]
Courses details #535

**Comment by mumacadam** [comment]
![Image](https://github.com/user-attachments/assets/862c10ba-bc48-4c39-9fb5-2f61ecfa2ed5)

let's make a rule where goals and objectives are fully visible (no scrolling bar), and description adapts to that ? (it's okay if the description has a scrolling bar).

Also, the scrolling bar should be redesigned according to the mock-up. can we have this more simplistic scrolling bar as in figma ?

**Comment by kevinmulier** [comment]
Solved but it's a bit hacky (won't work on window resizing -> not an expected user behavior) since css flexbox aren't made for that kind of dependent max height

**Comment by Rogzy-DB** [comment]
OK for me.
