### ISSUE TITLE
Tutorial - Thumbs design (desktop and mobile)

### ISSUE THREAD

**Issue by trigger-xyz** [DecouvreBitcoin/sovereign-university#496]

**Comment by mumacadam** [comment]
**visual discrepancies between the figma mock-up and what has been dev. 
please follow more careful the design asked in the future.** 

https://www.figma.com/design/1fto3tLdJH7hOcbQ7vT9dg/PlanB-Network---Work-in-progress?node-id=7036-5990&m=dev

![Image](https://github.com/user-attachments/assets/f1f84bc3-8885-4f27-9226-6087a8718c43)
