### ISSUE TITLE
Course - Review chapter

### ISSUE THREAD

**Issue by trigger-xyz** [DecouvreBitcoin/sovereign-university#497]

**Comment by mumacadam** [comment]
a few changes to make after review : 

https://www.figma.com/design/1fto3tLdJH7hOcbQ7vT9dg/PlanB-Network---Work-in-progress?node-id=7027-96628&m=dev


![Image](https://github.com/user-attachments/assets/d5cd8f56-bb41-4ba6-a8c1-a0a01321416e)

**Comment by mumacadam** [comment]
changes in data : 
change chapter name to "evaluate the course" and remove "feedback session"
Also for mobile, is it possible to not go

**Comment by Rogzy-DB** [comment]
SO this is where the chapter name in curriculum was talked about ^^. 

This issue is good to be closed. Their is already 2 new one regarding bug fixes in ready to dev (animation on stares), no mandatory fildes, and a next chapter button.

**Comment by mumacadam** [comment]
issue for data added into the data repository as PlanB-Network/bitcoin-educational-content#970

**Comment by mumacadam** [comment]
please add a skip review button at the end of the page. 

![Image](https://github.com/user-attachments/assets/5c8517b5-3ae6-4387-a116-6ca0750612c3)

https://www.figma.com/design/1fto3tLdJH7hOcbQ7vT9dg/PlanB-Network---Work-in-progress?node-id=7027-95819&m=dev

**Comment by mumacadam** [comment]
there is a bug I reported in another issue.
