### ISSUE TITLE
Professors page redesign

### ISSUE THREAD

**Issue by trigger-xyz** [DecouvreBitcoin/sovereign-university#502]

**Comment by kevinmulier** [comment]
Courses details and teacher profile : #535

**Comment by Rogzy-DB** [comment]
ok 

![Image](https://github.com/user-attachments/assets/3f0efe49-6cd6-4468-b9fe-707feb8ce36e)

![Image](https://github.com/user-attachments/assets/938d0495-8986-42e4-85e4-858ec8452609)
