### ISSUE TITLE
BUG: Issue with log in/log out

### ISSUE THREAD

**Issue by trigger-xyz** [DecouvreBitcoin/sovereign-university#532]
"J'etais co sur un compte. j'ai deco pour me co sur un autre.
j'ai deco du 2eme et j'etais automatiquement co au premier

en gros ca a pas detruit mon premier log in de me deco reco "

Dm Rogzy for more informations

**Comment by trigger-xyz** [comment]
Was not able to reproduce

**Comment by max-lt** [comment]
This is normal.
