### ISSUE TITLE
Update teacher card in course homepage

### ISSUE THREAD

**Issue by trigger-xyz** [DecouvreBitcoin/sovereign-university#550]
There is still the "old" teacher card design in the homepage.

Replace is with the new one, and remove old code if needed.

![Image](https://github.com/user-attachments/assets/aa55188c-2931-4b3b-864d-7438c1ae0314)

**Comment by trigger-xyz** [comment]
@Flashmaxi maybe a new task for you :)

**Comment by Flashmaxi** [comment]
Yes, I will take it @trigger67

**Comment by Rogzy-DB** [comment]
PLease include the URL link in Asi0 name ( orange). when going over, it should be in medium.  Beside this, all good. 

![Image](https://github.com/user-attachments/assets/178c93f6-3e4a-4bfd-af2d-161645b8ddac)

**Comment by Flashmaxi** [comment]
I added link and reduced font weight to normal when not hovering, on hover it is medium. If I understood that correctly @Rogzy-DB
