### ISSUE TITLE
[BUG] - LOIC MOREL AS A LINK to his professor page (underlign and orange hovering as for github repository

### ISSUE THREAD

**Issue by Flashmaxi** [DecouvreBitcoin/sovereign-university#566]

**Comment by Flashmaxi** [comment]
![Image](https://github.com/user-attachments/assets/55604948-8930-4db3-9167-7e496dc5e4e5)

**Comment by Rogzy-DB** [comment]
ok : ![Image](https://github.com/user-attachments/assets/cc1ed88b-7aa0-4d7b-b9b4-d8dd2560eb43)
