### ISSUE TITLE
Course - Quizz re-design

### ISSUE THREAD

**Issue by kevinmulier** [DecouvreBitcoin/sovereign-university#586]
https://www.figma.com/design/1fto3tLdJH7hOcbQ7vT9dg/PlanB-Network---Work-in-progress?node-id=7387-164426

Meurren on it

**Comment by Rogzy-DB** [comment]
2 Bug to fix: 

Question should always be on the left: 

![Image](https://github.com/user-attachments/assets/c0fcc923-8b26-41a5-b936-270e85a029ba)


The arrow changes size depending of the answer 

![Image](https://github.com/user-attachments/assets/dbd8cbe9-6031-4f27-94e7-2bc683704190)
