### ISSUE TITLE
[BUG] - not next button on review systeme

### ISSUE THREAD

**Issue by kevinmulier** [DecouvreBitcoin/sovereign-university#609]
Their is no way to skip this section. Please add next chapter button. 

![Image](https://github.com/user-attachments/assets/fb7d111a-db9e-43f0-b6c1-8cf5d1bb2bc7)

**Comment by mumacadam** [comment]
![Image](https://github.com/user-attachments/assets/5675f98d-328b-432a-ada1-6e6d059ad026)
 figma page ready 

https://www.figma.com/design/1fto3tLdJH7hOcbQ7vT9dg/PlanB-Network---Work-in-progress?node-id=7027-95819&m=dev
