### ISSUE TITLE
(bug] - Double twitter on Teacher

### ISSUE THREAD

**Issue by Rogzy-DB** [DecouvreBitcoin/sovereign-university#624]
Some teachers have 2 X account leading to a error 404 

Maybe it's on the data side. if it's the case, please forward the issue to the right person. 

![Image](https://github.com/user-attachments/assets/febb506c-5386-404b-8e65-50b457604b09)

**Comment by mumacadam** [comment]
![Image](https://github.com/user-attachments/assets/1381d890-5b20-4dde-98b8-68e1c5c80041)

the padding between the 2 social medias is different from a card to another. keep it like the smaller one - left on the picture.
