### ISSUE TITLE
Remotv LN auth from front

### ISSUE THREAD

**Issue by Rogzy-DB** [DecouvreBitcoin/sovereign-university#625]
If we can't be put back the LN auth option, then remove for now. 

if remove, remove also the "--------or------- "

![Image](https://github.com/user-attachments/assets/cd6d5c28-4ef3-4e29-b809-ff51147d98ac)

**Comment by Flashmaxi** [comment]
@trigger67 I commented out LN register & login part in the Form rework branch.
