### ISSUE TITLE
[bug] - Filter option in map fix 

### ISSUE THREAD

**Issue by Rogzy-DB** [DecouvreBitcoin/sovereign-university#628]
Filter option doesn't work. Remove or fix (can be removed for now)

![Image](https://github.com/user-attachments/assets/c6b189dc-9b52-41af-94de-a6fd0c3e7992)

**Comment by mumacadam** [comment]
mockup here with comments for changes 

https://www.figma.com/design/1fto3tLdJH7hOcbQ7vT9dg/PlanB-Network---Work-in-progress?node-id=8345-16945&m=dev

**Comment by mumacadam** [comment]
![Image](https://github.com/user-attachments/assets/fb527652-d12d-4d22-97b0-104149a50320)
 
as it is in the monthly view, we cannot view all events cause the events info is too big. 
Reduce it like on the dashboard to only one line, with the hovering effect that expands it.


![Image](https://github.com/user-attachments/assets/e91fc423-1882-4d5f-9e53-279cb2a0bdf4)

hovering 
![Image](https://github.com/user-attachments/assets/09d707d5-1d8b-4b0c-ada9-c4d493cac8e2)

**Comment by mumacadam** [comment]
there is also an issue with colours. I don't know why the colours are like that, but we need to change them to the same colour code as in the component (same as the one used in dashboard).
the component image has been dropped on the figma page.

![Image](https://github.com/user-attachments/assets/d0230c92-f341-4ff3-9312-a68d1001f65f)

**Comment by Flashmaxi** [comment]
Well I did not touch the colors, but no problem I can modify that.
