### ISSUE TITLE
[bug] - Calender on map too narrow on date

### ISSUE THREAD

**Issue by Rogzy-DB** [DecouvreBitcoin/sovereign-university#629]
The Calender option of the map display the week with only 4 hours or so. 

Let's just keep thing by full DAY and only should the monhtly view: 

![Image](https://github.com/user-attachments/assets/efe95fdc-3c7d-42f9-8767-214e14714885)

**Comment by mumacadam** [comment]
The change asked is to only put the calendar in monthly view - and not in weekly view like it is now. No need for figma mock-up because the original mock-up was like this. to be found in published version if needed.
