### ISSUE TITLE
Add date and place to curriculum

### ISSUE THREAD

**Issue by kevinmulier** [DecouvreBitcoin/sovereign-university#633]
![Image](https://github.com/user-attachments/assets/f56e64e7-ae7c-4863-afbb-4abbbe950dd5)

**Comment by Rogzy-DB** [comment]
I don't see it on my side ... windows

**Comment by kevinmulier** [comment]
![image](https://github.com/user-attachments/assets/08815d2e-3064-4242-a502-87da97873ca5)
Review chapter is available in the curriculum on mainnet

For the dates and places, if they are not added to the course markdown in the proper format (like it was done a few months ago for biz school), it won't show up
Remaining issue is data related @Rogzy-DB
