### ISSUE TITLE
Quizz creation integration

### ISSUE THREAD

**Issue by Rogzy-DB** [DecouvreBitcoin/sovereign-university#64]
## Quizz integration

Full intégration of a quizz systeme within th euniversity. 
1 quizz by chapter ( page , so when we have 2 ## within the markdown course structure), 1 final exam at the end of each courses. Quizz in multiple languages.

The details of the section (not chapter, does that mean we add all the chapter exam together ?? ) result should be added to the detaisl section fo the dashboard courses review

Front: 
one version for desktop, one version for mobile. quizz questions + results + reviews.

Exam integration:
https://www.figma.com/file/8N8qLeToPHxXmz0y3xLXAZ/University?type=design&node-id=519-13258&mode=dev 

Dashboard integration: https://www.figma.com/file/8N8qLeToPHxXmz0y3xLXAZ/University?type=design&node-id=17-7553&mode=dev

![Image](https://github.com/DecouvreBitcoin/sovereign-university/assets/131364678/90e6a7f9-6190-4daa-8fe4-e02c0bde605f)

![Image](https://github.com/DecouvreBitcoin/sovereign-university/assets/131364678/6558b64c-70c7-4141-bef1-8a29fa860d2a)

![Image](https://github.com/DecouvreBitcoin/sovereign-university/assets/131364678/9996d7e5-058d-4efb-a1b6-d9bfe39d1dd7)

Back: 

ASIO & LOUNES

"Add quizzes to all exam sections
Database

    Data of a question
        Question
        Correct answer
        Other answers
        Explanatory text
        Category / theme
        Date
        Author if personal quiz, linked courses otherwise
        Linked quiz
        Estimated difficulty and duration
        Additional tools if necessary
    Usable throughout the Academy
        When creating a quiz on a course
    Filters by theme, difficulty, author, topic, % of success

Quiz System

    Limits of attempts, time
    Questions in order or random
    Report in case of a problem (spelling mistake, wrong answer, etc.)
    Explanatory text in case of error or clarifications in case of success
    Rewards in points"

**Comment by Asi0Flammeus** [comment]
Based on what you asked, I propose the following format for storing all MCQs of the SovU: a simple JSON file that entirely define the question with couple of properties:
- `course`: name of the course from which the question belongs to
- `section`: section from which the question belongs to 
- `chapter`: chapter from which the question belongs to 
- `difficulty`: set to `easy`, `intermediary`, `hard`, or `expert`
- `duration`: estimation time in seconds to answer the question
- `author`: original question of the question
- `creation_date`: date of creation
- `update_date`: date  of last modification 
- `question`: short and unambiguous question 
- `options`: always 4 options are provided
- `answer`: index of the correct answer from options list (start at 0)
- `explanation`: short text to provide more context and/or external sources

Each JSON file is named by its UID of 4 intergers and located in a sub-subfolder (based on its language) in the corresponding course. 

 Here's an example: 

``` ascii

.
└── course
    └── btc101
        └── quizz
            └── en
                └── 0001.json
```

``` json
{
  "course": "BTC101",
  "section": 1,
  "chapter": 2,
  "difficulty": "easy",
  "duration": 30
  "author": "DecouvreBitcoin",
  "creation_date": "2023-09-18",
  "update_date": "2023-10-02",
  "question": "When was the Bitcoin protocol officially initiated?",
  "options": ["December 25, 2008", "January 1, 2009", "January 3, 2009", "February 11, 2009"],
  "answer": 2,
  "explanation": "As announced in the cypherpunk mailing list, the [Genesis Block](https://mempool.space/block/000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f) was minned the 3rd of January 2009 which launched the Bitcoin Protocol.",
}
```

**Comment by trigger67** [comment]
UI is done. Waiting for the backend to plug everything.
