### ISSUE TITLE
Show "paid courses" in user dashboard

### ISSUE THREAD

**Issue by trigger-xyz** [DecouvreBitcoin/sovereign-university#648]
When you pay a course, but did not do any chapter, it should appear in your dashboard (menu + main page)

**Comment by trigger-xyz** [comment]
Also when you click "start course" it will now appear in your dashboard.

Published on testnet and mainnet, and data fixed for previously bought courses.

FYI @mumacadam

**Comment by Rogzy-DB** [comment]
Ok for feree courses. COuldn't check for paid one
