### ISSUE TITLE
[BUG](events) - fix event cards

### ISSUE THREAD

**Issue by Flashmaxi** [DecouvreBitcoin/sovereign-university#649]
When all of the filters are active, bottom component renders all upcoming events inside of the event card spot. We don't want that behavior.

**Comment by Flashmaxi** [comment]
![Image](https://github.com/user-attachments/assets/1f8b2201-db5c-4892-8765-ba6697682206)

**Comment by mumacadam** [comment]
the filters should impact the map, but also the calendar simultaneously. 
Now only the map is impacted - not the calendar.
Please change it so that the calendar takes into account the filters choices.
