### ISSUE TITLE
course homepage v3

### ISSUE THREAD

**Issue by mumacadam** [DecouvreBitcoin/sovereign-university#653]
Small changes to make on the course homepage. Everything is explained on figma

https://www.figma.com/design/1fto3tLdJH7hOcbQ7vT9dg/PlanB-Network---Work-in-progress?node-id=8246-157750&m=dev

![Image](https://github.com/user-attachments/assets/3a425e7e-2b14-4ee9-9d2e-5356d317110d)

**Comment by mumacadam** [comment]
mobile version : research bar should be as wide as the course card. 

also for mobile and desktop, let's use the same frame for B-cert as the new one used in homepage. mock-up has been updated accordingly.

![Image](https://github.com/user-attachments/assets/952937c1-db57-4f5c-96ca-139d3d6467f3)

**Comment by Flashmaxi** [comment]
🫡
