### ISSUE TITLE
Remove fee distribution

### ISSUE THREAD

**Issue by trigger-xyz** [DecouvreBitcoin/sovereign-university#666]
We can remove the fee destribution at the botom 

![Image](https://github.com/user-attachments/assets/ad8f178d-4510-45e6-86e8-0817cf042cc2)

**Comment by mumacadam** [comment]
good that I see this, since I also need to remove them from the figma, to have an up-to-date figma file for the published version.
@trigger67 next time something like this has impacts on the mock-ups, please notify me.
