### ISSUE TITLE
Dashboard / Cours specific "overview & ratings"

### ISSUE THREAD

**Issue by mumacadam** [DecouvreBitcoin/sovereign-university#668]
These are the other tabs of a dedicated course section on the student dashboard.
Discussion to have about the rules to apply to the ratings : how long are they editable - not editable after a certain amount of time ? or after the student completes the course ?
the rest is quite straight forward.

https://www.figma.com/design/1fto3tLdJH7hOcbQ7vT9dg/PlanB-Network---Work-in-progress?node-id=7903-13039&m=dev

![Image](https://github.com/user-attachments/assets/80d7f21f-8c2f-4b51-a86d-614ab7cd36e2)

**Comment by Rogzy-DB** [comment]
Yo @kevinmulier  just created a new issue because you left the next button on this page.

**Comment by mumacadam** [comment]
@kevinmulier this was modified according to what we discussed.
mobile frames have been reviewed + the review section has been changed.
