### ISSUE TITLE
[BUG] Event Ticket generation 

### ISSUE THREAD

**Issue by Asi0Flammeus** [DecouvreBitcoin/sovereign-university#678]
I have download a ticket for my reservation of a bcert exam on testnet and some difference are present with the expected ticket:
- the quality of the image in the header should be increased
  - can this [one](https://github.com/user-attachments/assets/dfa7735f-199b-467a-87ba-c8d54b4bfed0) be used instead 
- also would be easier for logistic reason to add the username inside the qr code
- the symbol ₿ is not supported in the pdf
  - and it must be used for "organised by Plan ₿ Network"
- the box around the qrcode is missing and the ticket number and booking date too
- the pill at the bottom is missing too 

here is the [figma read-only link](https://www.figma.com/design/ZeeZcE7v8URvOOp9ymPEZ5/Bank-of-images?node-id=1747-169&t=PTsvWvvq6waicK9y-1) for reference. 

## expected 
![image](https://github.com/user-attachments/assets/9cabadac-1a66-4b01-9892-50b75b2dce80)
 
## actual 

![image](https://github.com/user-attachments/assets/c09eec93-dc69-460a-bc77-8835914aa894)

**Comment by mumacadam** [comment]
cannot test so I'll trust you.
