### ISSUE TITLE
Replace redirection for B-CERT charter button

### ISSUE THREAD

**Issue by Asi0Flammeus** [DecouvreBitcoin/sovereign-university#679]
In the BCERT page there's a button for the charter (see [screenshot](https://github.com/user-attachments/assets/ed2f7ad8-bb5c-4241-8689-6c3d153c0302)) which currently redirect to the homepage. Could the redirection link be changed to this link instead: 
https://workspace.planb.network/s/Q4HAkXkgaKwTHbA

**Comment by kevinmulier** [comment]
Waiting for confirmation as we previously used a kutt link so you can change the redirect on your end @Asi0Flammeus 

![Image](https://github.com/user-attachments/assets/0726220f-5357-40e3-960d-4291f40dafa3)

**Comment by Asi0Flammeus** [comment]
Ah! Yes thank you for reminding me that decision! I will therefore directly change the redirection url.
