### ISSUE TITLE
[bug] Division by Zero Error in completeChapterProcedure

### ISSUE THREAD

**Issue by max-lt** [DecouvreBitcoin/sovereign-university#688]
The `completeChapterProcedure` can fail badly (err: div by zero) when applied to a non-english course;
query `completeChapterQuery` can fail on `(chapter_count.completed_count::FLOAT / total_chapters.total)` if ` total_chapters.total` is `0`.

To reproduce:

 - Go to [testnet.planb.network](https://testnet.planb.network/fr/courses/btc205/a6410a99-adfc-50fd-a004-8048be620c8a)
 - Sign in
 - Set language to english
 - Submit a review

You will have a `"division by zero"` error response

**Comment by trigger-xyz** [comment]
Issue il linked to hardcoded `'en'`  in the query, and btc205 has no english version ...

We could have same issue with  the "getTickets" query that uses 'en'.

We need to update these 2 queries to make the code more robust to "non english" courses.
