### ISSUE TITLE
[bug] - Remove next button in review dashboard tab

### ISSUE THREAD

**Issue by kevinmulier** [DecouvreBitcoin/sovereign-university#722]
In review is the exact same componant but it should be a variable without the next chapter button because it's on the menu.

![Image](https://github.com/user-attachments/assets/2661b153-4cc5-4b2d-8342-6575d968eea4)

**Comment by mumacadam** [comment]
this will be discussed with Rogzy - cause I feel it's not the good way to go.

behaviour to check, cause when I click on submit review in dashboard, nothing happens. so I don't know if it has been taken into account.

also the public comment should be mandatory, like inside the course. 

so I realise that the public comment was mandatory before inside the course. but now it's not anymore. or it should be. 

Also I had a bug in a course, where there was the button "edit" for the feedback
