### ISSUE TITLE
Dashboard(course) - Rework mobile design

### ISSUE THREAD

**Issue by kevinmulier** [DecouvreBitcoin/sovereign-university#776]

**Comment by mumacadam** [comment]
could you make it so that when clicking on a course card (not only on the button) it goes to details ?

![Image](https://github.com/user-attachments/assets/264ac0d7-dcde-400e-a21c-c9457ef7ecb7)

**Comment by mumacadam** [comment]
also, this sentence now needs to be changed to "You haven't completed any course yet." in black (no link).


![Image](https://github.com/user-attachments/assets/0a884c11-a3bc-4670-91be-2dee2a4c36a0)
