### ISSUE TITLE
Integrate courses card in mark down (link preview)

### ISSUE THREAD

**Issue by kevinmulier** [DecouvreBitcoin/sovereign-university#778]
The same way we can now include the tutorial preview componant into a markdown with the link, we need to be able to do the same for the courses with the courses card: 

![Image](https://github.com/user-attachments/assets/7c64d0df-d73a-48ff-a8e0-5070aabaaa67)

**Comment by mumacadam** [comment]
do we have an example of how it looks integrated ?

**Comment by Rogzy-DB** [comment]
You can find one in BTC 101 - hyperinflation. 

But it's bugged: The link doesn't work and the animation is outside of it"s box @kevinmulier . Otherwise very good

![Image](https://github.com/user-attachments/assets/bd164b85-fd70-4d4f-b692-2fe00d2c4dad)
