### ISSUE TITLE
Ressources - NewsLetter page

### ISSUE THREAD

**Issue by trigger-xyz** [DecouvreBitcoin/sovereign-university#784]
Creation of the newsletter page!

https://www.figma.com/design/1fto3tLdJH7hOcbQ7vT9dg/PlanB-Network---Work-in-progress?node-id=6372-26868&t=sMhDrVLiMIjDWRrg-1

![Image](https://github.com/user-attachments/assets/e6c7add1-e170-462c-9f54-76013d99c9d0)

**Comment by mumacadam** [comment]
Figma mock-up finalized : 

https://www.figma.com/design/1fto3tLdJH7hOcbQ7vT9dg/PlanB-Network---Work-in-progress?node-id=10558-12211&m=dev
