### ISSUE TITLE
Dashboard(admin) - Bookings panel

### ISSUE THREAD

**Issue by mumacadam** [DecouvreBitcoin/sovereign-university#788]
section in admin dashboard for the admins to be able to easily download the list of participants. 

https://www.figma.com/design/1fto3tLdJH7hOcbQ7vT9dg/PlanB-Network---Work-in-progress?node-id=9611-84682&m=dev

![Image](https://github.com/user-attachments/assets/79447f4e-c415-4eac-8b7a-e64cd2796e8f)

**Comment by trigger-xyz** [comment]
I can see lots of former bookings + dates seems to be wrong @Flashmaxi 
![Image](https://github.com/user-attachments/assets/8c4e2d5d-d23f-4372-8df2-f53d0dfbedbd)

**Comment by Flashmaxi** [comment]
Looking into it @trigger67

**Comment by Rogzy-DB** [comment]
Also, we could reorder the date so the last one is at the top and not the bottom. So it's easier to navigate Thanks

**Comment by trigger-xyz** [comment]
Isn't it better to keep the order like it is today ?

When you are the day of an event, and want to download the participants, like that you do not have to scroll, it's on the top.

**Comment by Flashmaxi** [comment]
I agree with @trigger67 on this one I think best approach is to have them from most recent on top.
