### ISSUE TITLE
fix link

### ISSUE THREAD

**Issue by Rogzy-DB** [DecouvreBitcoin/sovereign-university#79]
Le bouton de la page d'acceuil devrait envoyer vers la page Node, pas le github. 

Les bouton de la page node vers le github par contre. 

![Image](https://github.com/DecouvreBitcoin/sovereign-university/assets/131364678/29d3e3da-a477-4768-b4f9-1a2b68c0ca8c)

**Comment by jramos0** [comment]
I worked on this and it's fix
