### ISSUE TITLE
Dashboard(admin) - Users with filters/sorting/paging

### ISSUE THREAD

**Issue by trigger-xyz** [DecouvreBitcoin/sovereign-university#790]

**Comment by mumacadam** [comment]
https://www.figma.com/design/1fto3tLdJH7hOcbQ7vT9dg/PlanB-Network---Work-in-progress?node-id=9779-20020&m=dev

![Image](https://github.com/user-attachments/assets/31b4d119-b3eb-4b9e-bd4d-17c12a540931)
