### ISSUE TITLE
Dashboard(teacher & admin) - Tutorials page

### ISSUE THREAD

**Issue by mumacadam** [DecouvreBitcoin/sovereign-university#793]
this section of the teacher dashboard is for the dashboard to see the analytics of his/her tutorials. 

mock-ups are ready : 

https://www.figma.com/design/1fto3tLdJH7hOcbQ7vT9dg/PlanB-Network---Work-in-progress?node-id=9639-100967&m=dev

![Image](https://github.com/user-attachments/assets/03a6a346-2d9b-4cb6-a765-ed630d1c8c20)

**Comment by mumacadam** [comment]
I cannot review this, since I don't have an admin or teacher account on testnet. any credentials to give me so I can review ?

**Comment by trigger-xyz** [comment]
@mumacadam `mumu_macadam2` is now superadmin on testnet

**Comment by trigger-xyz** [comment]
Also `macadam_mumu` is already a teacher

**Comment by mumacadam** [comment]
don't know what's happening but it doesn't work on my laptop (safari). when I click on any of the tabs of the admin menu (user roles/tutos/bookings) nothing happens.

**Comment by kevinmulier** [comment]
Can you try logging out/in again ? Might be a session issue as I don't have this issue on my safari's equivalent @mumacadam

**Comment by Rogzy-DB** [comment]
Works on admin, doesn't seems to work for Teacher. @LoicPandul  say he sends back to courses instead of tutorial.

**Comment by LoicPandul** [comment]
Sorry, I spoke too soon ^^. I actually had the same issue at first, just like Rogzy mentioned, but after logging out/in, it started working again. Refreshing and hard refreshing didn’t work. Tested on Firefox and Chrome.

**Comment by trigger-xyz** [comment]
We should have explained you how that works : 

Specific access rights (admin/professor) are set when the user log in.
So if we add new rights to people, they will not see the new features related to their new role, until the logout/login again.
