### ISSUE TITLE
redesign - Course - quotes & course preview

### ISSUE THREAD

**Issue by mumacadam** [DecouvreBitcoin/sovereign-university#817]
quotes redesign + the course preview of issue as it should look like.

https://www.figma.com/design/1fto3tLdJH7hOcbQ7vT9dg/PlanB-Network---Work-in-progress?node-id=9919-18122&m=dev

![Image](https://github.com/user-attachments/assets/114ab505-1b18-4619-a281-647fa2b1010a)

**Comment by Flashmaxi** [comment]
I fixed layout issue on navigation panel ![Image](https://github.com/user-attachments/assets/8262e19a-25d6-4e40-bde8-1d990a19ddc8)
scroll was always there so it looked ugly tbh 
now it looks like this ![Image](https://github.com/user-attachments/assets/dae7fc09-0c18-4e60-9d76-6a1d223205c9)
and it will show properly when expanded ![Image](https://github.com/user-attachments/assets/ff702a29-27ff-4f7c-b811-22289924b64a)




@mumacadam
