### ISSUE TITLE
Course homepage - BTC101 emphasis

### ISSUE THREAD

**Issue by mumacadam** [DecouvreBitcoin/sovereign-university#827]
BTC101 card to stand out on course homepage + redesign of the course header menu.
the idea is to have a "start here" tag onto BTC101 only - and BTC101 as the first and different card on top of the card list.
+ to have it stand out in the menu

https://www.figma.com/design/1fto3tLdJH7hOcbQ7vT9dg/PlanB-Network---Work-in-progress?node-id=9992-8942&m=dev

mock-up is ready : 

![Image](https://github.com/user-attachments/assets/a3b5d16a-4512-4fc5-9014-6f20f4164757)

**Comment by trigger-xyz** [comment]
We separated the issue for the course emphasis, and the menu.
This is just the course emphasis.
