### ISSUE TITLE
[FRONT] harmonise front for resource and repair bug

### ISSUE THREAD

**Issue by mumacadam** [DecouvreBitcoin/sovereign-university#851]
harmonise resource page (bug in the frames). and take the opportunity to also harmonise the conference replays with the rest.
instructions are given in comment in the figma 

https://www.figma.com/design/1fto3tLdJH7hOcbQ7vT9dg/PlanB-Network---Work-in-progress?node-id=10209-98603&m=dev

![Image](https://github.com/user-attachments/assets/e11947e1-1cd8-441a-8a18-21b8f93a859a)

**Comment by Rogzy-DB** [comment]
I don't see the thumb on the texte. Maybe internet issues from the aeroport. 

Also i tested it in FR and the next was not orange ( bur orange on ENG). How do we deal with coloring a texte and making translated ? if impossible let's talk about it.

**Comment by trigger-xyz** [comment]
=> Dev: remove translations so that translators redo them. That will add the orange color
