### ISSUE TITLE
[bug] - resize of BET vignette

### ISSUE THREAD

**Issue by trigger-xyz** [DecouvreBitcoin/sovereign-university#862]
Somehow the vignette got resized differently and aren't all the same anyone

![Image](https://github.com/user-attachments/assets/37534e29-fc98-4d5a-aaca-34e43e69b754)

**Comment by Rogzy-DB** [comment]
Error remain on mobile version.

**Comment by kevinmulier** [comment]
Will figure it out on mobile as well, oversight on my part 

Issues are probably related to changes that were made a while ago when introducing public communication part as far as I saw in the code, vertical cards code was changed at that time
