### ISSUE TITLE
search bar little improvement

### ISSUE THREAD

**Issue by mumacadam** [DecouvreBitcoin/sovereign-university#874]
for the search bar with filters that was developed in the courses homepage, when the user uses the filter and then scrolls out of the search bar, the info that is filtered is not indicated anywhere, and it's missing.

so I'd like the filters selected to be indicated in the search bar after being selected : 

https://www.figma.com/design/1fto3tLdJH7hOcbQ7vT9dg/PlanB-Network---Work-in-progress?node-id=10507-56863&m=dev

![Image](https://github.com/user-attachments/assets/85f5f588-ee2d-439a-a4de-87574d35febb)

**Comment by kevinmulier** [comment]
https://www.figma.com/design/1fto3tLdJH7hOcbQ7vT9dg/PlanB-Network---Work-in-progress?m=dev
-> new link
