### ISSUE TITLE
[FRONT]  title and padding in final exam padding

### ISSUE THREAD

**Issue by mumacadam** [DecouvreBitcoin/sovereign-university#875]
font change and add padding in final exam page in mobile 

https://www.figma.com/design/1fto3tLdJH7hOcbQ7vT9dg/PlanB-Network---Work-in-progress?node-id=10511-65062&m=dev

![Image](https://github.com/user-attachments/assets/706ee601-865f-4dbc-a214-abb095babb13)

**Comment by Flashmaxi** [comment]
Muriel proofreading was not accounted for in this mock up 
![389945117-25b8fa87-2626-4c83-9cb6-67e273af9c88](https://github.com/user-attachments/assets/023c6f28-27bd-4ecb-b9bd-f8331eae966f)
this is before

I added margin top to mobile component so title is visible, if that is okay with you we can merge it 
![389945022-732839b4-c233-417a-b658-fb4fc02b3fe2](https://github.com/user-attachments/assets/ce81da6e-5ed8-4634-b489-2461ab947f4d)
this is the change

**Comment by Rogzy-DB** [comment]
The "final exam" name isn't following the figma design (from what i was told), It should be centered.

**Comment by Flashmaxi** [comment]
@Rogzy-DB you can ignore comments from above it is different on testnet or mainnet now Kevin did adjustments as part of different ticket
