### ISSUE TITLE
Tutorial - Categories ordering

### ISSUE THREAD

**Issue by trigger-xyz** [DecouvreBitcoin/sovereign-university#877]
Can we have bitcoin & LN first, and then RGB as a 3rd category ?  or is it Data related

![Image](https://github.com/user-attachments/assets/b303aa6a-6952-4cf2-8fdd-d2c5455339f7)

**Comment by kevinmulier** [comment]
Current order seems totally random (different in local, on testnet and on mainnet)
We could force a specific order (alphabetical for instance?)

What do you think about that ? Any other idea @trigger67 @Rogzy-DB ?

**Comment by Rogzy-DB** [comment]
We should have a hard coded order. We can have @LoicPandul to decide them

**Comment by LoicPandul** [comment]
I agree with the order Bitcoin-LN-RGB 👍

**Comment by LoicPandul** [comment]
Actually, there is already an order defined in the bullet list on the left. That order seems good to me.
![.](https://github.com/user-attachments/assets/e33deef1-131f-4484-b2d0-ce14b3c489bd)
