### ISSUE TITLE
[Bug] Handle missing timezone for bookable events in dashboard queries

### ISSUE THREAD

**Issue by kevinmulier** [DecouvreBitcoin/sovereign-university#881]
Currently, queries in the dashboard Bookings fail when booked events lack a timezone

Proposed fix:

- Set a default timezone during the event insertion process ?
- Trigger an error during synchronization if an event lacks a timezone to detect it easily ?

Reproduce:

Query the dashboard Bookings with booked events missing a timezone

**Comment by trigger-xyz** [comment]
What exactly is the issue with the dasboard's bookings ?
Cant't we just check the timezone there and fix it ?
