### ISSUE TITLE
Bug - Course card UI

### ISSUE THREAD

**Issue by trigger-xyz** [DecouvreBitcoin/sovereign-university#919]

**Comment by Rogzy-DB** [comment]
I have no idea what i'm supposed to review

**Comment by Flashmaxi** [comment]
Same like with course card but in course suggestions in curriculum. @Rogzy-DB

**Comment by Rogzy-DB** [comment]
Nop.. sorry i still don't understand. I let you move this to reviewed if it's done. Please provide screenshot next time so it's easier.
