### ISSUE TITLE
Fix: modify course cards

### ISSUE THREAD

**Issue by Flashmaxi** [DecouvreBitcoin/sovereign-university#928]
https://www.figma.com/design/1fto3tLdJH7hOcbQ7vT9dg/PlanB-Network---Work-in-progress?node-id=9421-120226&node-type=canvas&m=dev

**Comment by Flashmaxi** [comment]
![Image](https://github.com/user-attachments/assets/a07bcb5a-682f-44a1-84f6-1e50666bd838)

**Comment by Rogzy-DB** [comment]
I have no idea what i'm supposed to review

**Comment by Flashmaxi** [comment]
Hey @Rogzy-DB we changed the position of star rating and few smaller modification. So it is more friendly with languages with long words like vietnamese.  Tags and star ratings were previously on same line now star rating is moved to a new line.
