### ISSUE TITLE
[BUG] - Log in content on mobile too large / no container

### ISSUE THREAD

**Issue by kevinmulier** [DecouvreBitcoin/sovereign-university#937]
![Image](https://github.com/user-attachments/assets/a58e7f89-946b-4896-a399-2d7c91aba05a)

**Comment by kevinmulier** [comment]
Could it be related to recent changes on payment pop-up ? @trigger67

**Comment by Rogzy-DB** [comment]
Good on my Phone, can't review on other format

**Comment by mumacadam** [comment]
it's working on my phone.
But there should be a lot more vertical padding. 
Please modify accordingly to published version file : https://www.figma.com/design/tMF1XLG6fPvrBqvxcldGE9/Plan-B-Network---Published-version?node-id=800-13606&m=dev

![Image](https://github.com/user-attachments/assets/03469cf7-c57e-4fc6-8b2f-588f24703335)
![Image](https://github.com/user-attachments/assets/429cb53c-9df9-4c82-8d23-504f408cb037)
